# Generated by Django 4.0.4 on 2023-01-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('studentKey', models.IntegerField(unique=True)),
                ('facultyKey', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'unique_together': {('code', 'name')},
            },
        ),
    ]
