# Generated by Django 4.1.5 on 2023-01-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_alter_course_options_alter_course_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='course',
            name='facultyKey',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='studentKey',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'name')},
        ),
    ]
