# Generated by Django 4.1.5 on 2023-01-31 15:02

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_alter_course_options_alter_course_facultykey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('description', froala_editor.fields.FroalaField()),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.course')),
            ],
            options={
                'verbose_name_plural': 'Announcements',
                'ordering': ['-datetime'],
            },
        ),
    ]
