# Generated by Django 4.1.5 on 2023-02-02 13:50

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0005_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
