# Generated by Django 4.1.3 on 2023-01-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iso', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
